import { getAllPublished } from "@ac/md";
import Head from "next/head";
import Link from "next/link";
import { PropsWithChildren } from "react";

export default function Home({ posts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <aside className="flex-col font-bold text-white hidden lg:flex lg:w-[10%] bg-blue-500 p-4 fixed h-full text-center">
          <Link href="#about" className="hover:underline text-lg">
            About me
          </Link>
          <Link href="#projects" className="hover:underline text-lg">
            Projects
          </Link>
          <Link href="#posts" className="hover:underline text-lg">
            Blog
          </Link>
        </aside>
        <main className="bg-white float-right lg:pl-[10%]">
          <section className="p-16">
            <h1 className="text-3xl font-bold">Alex Chadwick</h1>
            <h3 className="text-gray-800">
              Full Stack Web Developer
            </h3>
            <p className="text-gray-500 text-xs">
              Cambridge, United Kingdom
            </p>
          </section>
          <section className="p-16 bg-gray-300" id="about">
            <h1 className="text-3xl font-bold">About me</h1>
            <p className="mt-1">
              Having worked over the last 17 months on internal tooling for our
              teams, I have been able to refine my communication skills in order
              to efficiently and easily extract requirements from the end users.
            </p>
            <p className="mt-1">
              I take pride in my eagerness and ability to learn and adapt to new
              environments. It is thanks to this that I have been able to get to
              where I am today.
            </p>
            <p className="mt-1">
              I enjoy reading about code calisthenics and also partake in
              discussions about these and good practices, as I often find that
              the best code, is the code that is written for developers to build
              on. In fact, I often talk about these topics in blog articles,
              that I have written both on my personal Hashnode blog (which is
              being migrated over to this site) and for{" "}
              <a href="https://unicorn-utterances.com/unicorns/alexchadwick">
                Unicorn Utterances
              </a>
              .
            </p>
          </section>
          <section className="p-16 bg-gray-200" id="projects">
            <h1 className="text-3xl font-bold">Projects</h1>
            <p className="mt-1">
              These projects are the ones that I am actively working on or most
              proud of:
            </p>
            <div className="grid lg:grid-cols-3 gap-6 mt-2">
              <ProjectCard
                title="Brontobase"
                link="https://github.com/AlexChadwickP/brontobase"
              >
                <p >
                  Brontobase is a simple alternative to Supabase and PocketBase,
                  aimed to be simplistic, easy to setup and with a small
                  learning curve. This comes at the cost of customizability, but
                  it is not intended for complex projects or scalability, but
                  rather for beginners, small projects and prototyping
                </p>
                <hr className="m-2" />
                <p >Tech stack:</p>
                <ul className="list-disc list-inside">
                  <li >SQLite database</li>
                  <li >TypeScript</li>
                  <li >Deno runtime</li>
                  <li >Oak web framework</li>
                </ul>
              </ProjectCard>
              <ProjectCard
                title="ProgLang"
                link="https://github.com/AlexChadwickP/proglang"
              >
                <p >
                  ProgLang started out as an attempt to implement Forth in Rust,
                  and then I started designing the language myself. It is very
                  early, and the objective of this project is to learn how a
                  programming language works, rather than inventing a new
                  general purpose language
                </p>
                <hr className="m-2" />
                <p >Tech stack:</p>
                <ul className="list-disc list-inside">
                  <li >Rust</li>
                  <li >Cargo</li>
                </ul>
              </ProjectCard>
              <ProjectCard
                title="CLI Text Editor in C"
                link="https://github.com/AlexChadwickP/proglang"
              >
                <p >
                  A very simple CLI text editor written in C
                </p>
                <hr className="m-2" />
                <p >Tech stack:</p>
                <ul className="list-disc list-inside">
                  <li >C</li>
                  <li >Make</li>
                </ul>
              </ProjectCard>
            </div>
          </section>
          {!!posts && (
            <section id="posts" className="p-16 bg-gray-300 grid grid-cols-1 gap-4">
              {posts.map((post: any) => (
                <article key={post.slug} className='bg-white py-4 px-10'>
                  <Link href={`blog/${post.slug}`} className="text-2xl font-bold hover:underline">
                    {post.frontmatter.title}
                  </Link>
                  <p className='text-gray-800 text-lg'>{post.frontmatter.description}</p>
                </article>
              ))}
            </section>
          )}
        </main>
      </div>
    </>
  );
}

const ProjectCard = ({
  title,
  link,
  children,
}: PropsWithChildren & { title: string; link: string }) => {
  return (
    <div className="shadow-md p-4 bg-white rounded-lg">
      <h3 className="font-bold text-xl">{title}</h3>
      <div className="p-2">{children}</div>
      <a
        href={link}
        className="px-2 py-1 bg-blue-500 hover:bg-blue-400 text-white rounded-md"
      >
        Repository
      </a>
    </div>
  );
};

export const getStaticProps = async () => {
  const posts = getAllPublished("posts");

  return {
    props: { posts },
  };
};
